# Generated by Django 6.0.4 on 2026-05-18 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id_entrepot', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('typeentrepot', models.CharField(blank=True, max_length=20, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'entrepot',
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id_profile_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_profile', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Profile User',
                'verbose_name_plural': 'Profile Users',
                'db_table': 'profile_user',
            },
        ),
        migrations.CreateModel(
            name='CategorieProd',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cat', models.CharField(max_length=50)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'categorie_prod',
                'indexes': [models.Index(fields=['synchroniser'], name='categorie_p_synchro_293883_idx')],
            },
        ),
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id_concurrent', models.AutoField(primary_key=True, serialize=False)),
                ('nom_concurrent', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_ht', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('prix_carton', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('id_marque', models.IntegerField(blank=True, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'concurrent',
                'indexes': [models.Index(fields=['prix_ht'], name='concurrent_prix_ht_ac3ac9_idx'), models.Index(fields=['id_marque'], name='concurrent_id_marq_0bc664_idx'), models.Index(fields=['synchroniser'], name='concurrent_synchro_8c91ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id_correction', models.AutoField(primary_key=True, serialize=False)),
                ('nom_correction', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'correction',
                'indexes': [models.Index(fields=['synchroniser'], name='correction_synchro_6aabce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipe', models.CharField(max_length=20, unique=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'equipe',
                'indexes': [models.Index(fields=['synchroniser'], name='equipe_synchro_c8e9a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilleProd',
            fields=[
                ('id_famille', models.AutoField(primary_key=True, serialize=False)),
                ('nom_famille', models.CharField(max_length=50)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'famille_prod',
                'indexes': [models.Index(fields=['synchroniser'], name='famille_pro_synchro_fd245e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id_investissement', models.AutoField(primary_key=True, serialize=False)),
                ('nom_investissement', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'investissement',
                'indexes': [models.Index(fields=['synchroniser'], name='investissem_synchro_9c1cf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarqueProd',
            fields=[
                ('id_marque', models.AutoField(primary_key=True, serialize=False)),
                ('nom_marque', models.CharField(max_length=50)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'marque_prod',
                'indexes': [models.Index(fields=['synchroniser'], name='marque_prod_synchro_03e6da_idx')],
            },
        ),
        migrations.CreateModel(
            name='MvtEntrepot',
            fields=[
                ('id_mvt_entrepot', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_mvt_entrepot', models.DateField(blank=True, null=True)),
                ('entrepot_source', models.CharField(blank=True, max_length=50, null=True)),
                ('entrepot_destination', models.CharField(blank=True, max_length=50, null=True)),
                ('valider', models.CharField(default='Non', max_length=5)),
                ('mode_mvt_entrepot', models.CharField(blank=True, max_length=10, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'mvtentrepot',
                'indexes': [models.Index(fields=['date_mvt_entrepot'], name='mvtentrepot_date_mv_66517c_idx'), models.Index(fields=['entrepot_source'], name='mvtentrepot_entrepo_cd8050_idx'), models.Index(fields=['entrepot_destination'], name='mvtentrepot_entrepo_206f6e_idx'), models.Index(fields=['valider'], name='mvtentrepot_valider_c385e3_idx'), models.Index(fields=['synchroniser'], name='mvtentrepot_synchro_a1861e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id_packaging', models.AutoField(primary_key=True, serialize=False)),
                ('nom_packaging', models.CharField(max_length=20)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'packaging',
                'indexes': [models.Index(fields=['synchroniser'], name='packaging_synchro_41184b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_ht', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('prix_carton', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('conditionnement', models.CharField(blank=True, max_length=20, null=True)),
                ('prix_semi_gros', models.CharField(blank=True, max_length=20, null=True)),
                ('prix_achat_pdv', models.CharField(blank=True, max_length=20, null=True)),
                ('prix_consommateur', models.CharField(blank=True, max_length=20, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
                ('id_categorie', models.ForeignKey(blank=True, db_column='id_categorie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorieprod')),
                ('id_famille', models.ForeignKey(blank=True, db_column='id_famille', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.familleprod')),
                ('id_marque', models.ForeignKey(blank=True, db_column='id_marque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.marqueprod')),
                ('id_packaging', models.ForeignKey(blank=True, db_column='id_packaging', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.packaging')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='DetailMvtEntrepot',
            fields=[
                ('id_detail_reappro', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
                ('id_mvt_entrepot', models.ForeignKey(db_column='id_mvt_entrepot', on_delete=django.db.models.deletion.CASCADE, to='dashboard.mvtentrepot')),
                ('id_produit', models.ForeignKey(db_column='id_produit', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit')),
            ],
            options={
                'db_table': 'detailmvtentrepot',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id_secteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_secteur', models.CharField(max_length=20, unique=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
                ('id_equipe', models.ForeignKey(blank=True, db_column='id_equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipe')),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_boutique', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('nom_gerant', models.CharField(max_length=200)),
                ('tel_gerant', models.CharField(max_length=20)),
                ('statut', models.CharField(max_length=20)),
                ('id_user', models.CharField(blank=True, max_length=50, null=True)),
                ('cat', models.CharField(max_length=50)),
                ('sub_cat', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('arrond', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('valider', models.CharField(default='Oui', max_length=5)),
                ('photo', models.TextField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=20, null=True)),
                ('groupe', models.CharField(blank=True, max_length=20, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
                ('id_equipe', models.ForeignKey(blank=True, db_column='id_equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipe')),
                ('id_secteur', models.ForeignKey(blank=True, db_column='id_secteur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.secteur')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='StockEntrepot',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
                ('id_entrepot', models.ForeignKey(db_column='id_entrepot', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.entrepot')),
                ('id_produit', models.ForeignKey(db_column='id_produit', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit')),
            ],
            options={
                'db_table': 'stockentrepot',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('tel_user', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_user', models.CharField(blank=True, max_length=100, null=True)),
                ('id_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.CharField(default='Non', max_length=4)),
                ('activer', models.CharField(blank=True, default='Oui', max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('groupe', models.CharField(blank=True, max_length=20, null=True)),
                ('synchroniser', models.CharField(blank=True, max_length=5, null=True)),
                ('id_equipe', models.ForeignKey(blank=True, db_column='id_equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipe')),
                ('id_profile_user', models.ForeignKey(blank=True, db_column='id_profile_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profileuser')),
                ('id_secteur', models.ForeignKey(blank=True, db_column='id_secteur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.secteur')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='SuiviUser',
            fields=[
                ('id_suivi_user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_suivi', models.DateField(blank=True, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('imei', models.CharField(max_length=50)),
                ('login', models.ForeignKey(blank=True, db_column='login', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur')),
            ],
            options={
                'db_table': 'suiviuser',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id_planning', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_planning', models.DateField()),
                ('valider', models.CharField(max_length=5)),
                ('realiser', models.CharField(max_length=10)),
                ('ajouter_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('synchro_sup', models.CharField(blank=True, max_length=5, null=True)),
                ('synchro_admin', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(db_column='login', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.utilisateur')),
            ],
            options={
                'db_table': 'planning',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id_parcours', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField(default='00:00:00')),
                ('heure_fin', models.TimeField(default='00:00:00')),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('login', models.ForeignKey(blank=True, db_column='login', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur')),
            ],
            options={
                'db_table': 'parcours',
            },
        ),
        migrations.AddField(
            model_name='entrepot',
            name='login',
            field=models.ForeignKey(db_column='login', on_delete=django.db.models.deletion.PROTECT, to='dashboard.utilisateur'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('montant_vente', models.FloatField(default=0)),
                ('montant_payer', models.FloatField(default=0)),
                ('montant_restant', models.IntegerField(default=0)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('remise', models.IntegerField(blank=True, default=0, null=True)),
                ('synchro_admin', models.CharField(blank=True, max_length=5, null=True)),
                ('synchro_sup', models.CharField(blank=True, max_length=5, null=True)),
                ('login', models.ForeignKey(blank=True, db_column='login', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur')),
            ],
            options={
                'db_table': 'vente',
            },
        ),
        migrations.CreateModel(
            name='DetailsVente',
            fields=[
                ('id_detail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
                ('prix_vente', models.FloatField(default=0)),
                ('id_produit', models.ForeignKey(blank=True, db_column='id_produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.produit')),
                ('id_vente', models.ForeignKey(db_column='id_vente', on_delete=django.db.models.deletion.CASCADE, to='dashboard.vente')),
            ],
            options={
                'db_table': 'detailsvente',
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id_visite', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('synchro_sup', models.CharField(max_length=5)),
                ('en_local', models.CharField(blank=True, max_length=5, null=True)),
                ('synchro_admin', models.CharField(blank=True, max_length=5, null=True)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.client')),
                ('id_planning', models.ForeignKey(blank=True, db_column='id_planning', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.planning')),
                ('login', models.ForeignKey(blank=True, db_column='login', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur')),
            ],
            options={
                'db_table': 'visite',
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='id_visite',
            field=models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.visite'),
        ),
        migrations.CreateModel(
            name='DetailsVisiteProduit',
            fields=[
                ('id_details', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('prix_carton', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('position_produit', models.TextField(blank=True, null=True)),
                ('presence', models.CharField(blank=True, max_length=5, null=True)),
                ('id_produit', models.ForeignKey(blank=True, db_column='id_produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.produit')),
                ('id_visite', models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.visite')),
            ],
            options={
                'db_table': 'detailsvisiteproduit',
            },
        ),
        migrations.CreateModel(
            name='DetailsVisiteInvestissement',
            fields=[
                ('id_details', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('etat', models.CharField(blank=True, max_length=10, null=True)),
                ('presence', models.CharField(blank=True, max_length=5, null=True)),
                ('id_investissement', models.ForeignKey(blank=True, db_column='id_investissement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.investissement')),
                ('id_visite', models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.visite')),
            ],
            options={
                'db_table': 'detailsvisiteinvestissement',
            },
        ),
        migrations.CreateModel(
            name='DetailsVisiteCorrection',
            fields=[
                ('id_details', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_correction', models.ForeignKey(blank=True, db_column='id_correction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.correction')),
                ('id_visite', models.ForeignKey(db_column='id_visite', on_delete=django.db.models.deletion.CASCADE, to='dashboard.visite')),
            ],
            options={
                'db_table': 'detailsvisitecorrection',
            },
        ),
        migrations.CreateModel(
            name='DetailsVisiteConcurrent',
            fields=[
                ('id_details', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('prix_carton', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('prix_vente', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('position_produit', models.TextField(blank=True, null=True)),
                ('presence', models.CharField(blank=True, max_length=5, null=True)),
                ('nom_concurrent', models.CharField(max_length=50)),
                ('id_visite', models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.visite')),
            ],
            options={
                'db_table': 'detailsvisiteconcurrent',
            },
        ),
        migrations.CreateModel(
            name='DerniereVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.ForeignKey(db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('id_visite', models.ForeignKey(db_column='id_visite', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.visite')),
            ],
            options={
                'db_table': 'dernierevisite',
            },
        ),
        migrations.CreateModel(
            name='DetailDernierVisite',
            fields=[
                ('id_detail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, max_length=100, null=True)),
                ('id_marque', models.IntegerField(default=0)),
                ('id_visite', models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dernierevisite')),
            ],
            options={
                'db_table': 'detaildernieravisite',
                'indexes': [models.Index(fields=['id_visite'], name='detailderni_id_visi_363eae_idx'), models.Index(fields=['article'], name='detailderni_article_d39091_idx'), models.Index(fields=['id_marque'], name='detailderni_id_marq_fc96a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanningClient',
            fields=[
                ('id_planning_client', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('visiter', models.CharField(max_length=20)),
                ('id_client', models.ForeignKey(db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('id_planning', models.ForeignKey(db_column='id_planning', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.planning')),
            ],
            options={
                'db_table': 'planning_client',
                'indexes': [models.Index(fields=['id_planning'], name='planning_cl_id_plan_034f95_idx'), models.Index(fields=['visiter'], name='planning_cl_visiter_6efccc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['prix_ht'], name='produit_prix_ht_0cdcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['id_marque'], name='produit_id_marq_d78eec_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['id_famille'], name='produit_id_fami_30f9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['id_categorie'], name='produit_id_cate_df4c19_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['id_packaging'], name='produit_id_pack_b13b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['synchroniser'], name='produit_synchro_c07637_idx'),
        ),
        migrations.AddIndex(
            model_name='detailmvtentrepot',
            index=models.Index(fields=['id_mvt_entrepot'], name='detailmvten_id_mvt__316925_idx'),
        ),
        migrations.AddIndex(
            model_name='detailmvtentrepot',
            index=models.Index(fields=['id_produit'], name='detailmvten_id_prod_da4774_idx'),
        ),
        migrations.AddIndex(
            model_name='secteur',
            index=models.Index(fields=['synchroniser'], name='secteur_synchro_99cedc_idx'),
        ),
        migrations.AddIndex(
            model_name='secteur',
            index=models.Index(fields=['id_equipe'], name='secteur_id_equi_36c535_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['synchroniser'], name='client_synchro_69a088_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['quantite'], name='stockentrep_quantit_28322a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['id_produit'], name='stockentrep_id_prod_b74da9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['id_entrepot'], name='stockentrep_id_entr_aa1ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['synchroniser'], name='stockentrep_synchro_2d404d_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['id_equipe'], name='utilisateur_id_equi_855341_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['id_secteur'], name='utilisateur_id_sect_02dd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['id_profile_user'], name='utilisateur_id_prof_6785f4_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['synchroniser'], name='utilisateur_synchro_eddcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='suiviuser',
            index=models.Index(fields=['login'], name='suiviuser_login_b5796e_idx'),
        ),
        migrations.AddIndex(
            model_name='suiviuser',
            index=models.Index(fields=['date_suivi'], name='suiviuser_date_su_a9419e_idx'),
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(fields=['user'], name='planning_login_0f090b_idx'),
        ),
        migrations.AddIndex(
            model_name='parcours',
            index=models.Index(fields=['login'], name='parcours_login_90694d_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepot',
            index=models.Index(fields=['login'], name='entrepot_login_eef263_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepot',
            index=models.Index(fields=['typeentrepot'], name='entrepot_typeent_457bea_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepot',
            index=models.Index(fields=['synchroniser'], name='entrepot_synchro_5590fb_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvente',
            index=models.Index(fields=['id_vente'], name='detailsvent_id_vent_2975c9_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvente',
            index=models.Index(fields=['id_produit'], name='detailsvent_id_prod_fac52f_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['id_client'], name='visite_id_clie_45964a_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['login'], name='visite_login_79705e_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['id_planning'], name='visite_id_plan_dfaf09_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['login'], name='vente_login_fba7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['id_visite'], name='vente_id_visi_42f568_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteproduit',
            index=models.Index(fields=['id_visite'], name='detailsvisi_id_visi_07d856_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteproduit',
            index=models.Index(fields=['id_produit'], name='detailsvisi_id_prod_437258_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteinvestissement',
            index=models.Index(fields=['id_visite'], name='detailsvisi_id_visi_5657ea_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteinvestissement',
            index=models.Index(fields=['id_investissement'], name='detailsvisi_id_inve_2c515e_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisitecorrection',
            index=models.Index(fields=['id_visite'], name='detailsvisi_id_visi_6fc715_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisitecorrection',
            index=models.Index(fields=['id_correction'], name='detailsvisi_id_corr_1f90d8_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteconcurrent',
            index=models.Index(fields=['id_visite'], name='detailsvisi_id_visi_fc3abb_idx'),
        ),
        migrations.AddIndex(
            model_name='detailsvisiteconcurrent',
            index=models.Index(fields=['nom_concurrent'], name='detailsvisi_nom_con_2607bc_idx'),
        ),
        migrations.AddIndex(
            model_name='dernierevisite',
            index=models.Index(fields=['id_client'], name='dernierevis_id_clie_59f1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='dernierevisite',
            index=models.Index(fields=['id_visite'], name='dernierevis_id_visi_dd1339_idx'),
        ),
    ]
