# Generated by Django 6.0.4 on 2026-05-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='synchro_admin',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='synchro_sup',
        ),
    ]
