# Generated by Django 6.0.4 on 2026-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_planning_synchro_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dernierevisite',
            name='date_visite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dernierevisite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
