# Generated by Django 6.0.4 on 2026-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dernierevisite_date_visite_alter_dernierevisite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
