# Generated by Django 6.0.4 on 2026-05-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_client_arrond_alter_client_quartier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='synchro_sup',
            new_name='synchroniser',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='synchro_admin',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='synchro_sup',
        ),
        migrations.RemoveField(
            model_name='visite',
            name='en_local',
        ),
        migrations.RemoveField(
            model_name='visite',
            name='synchro_admin',
        ),
    ]
