# Generated by Django 6.0.4 on 2026-05-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_synchro_sup_visite_synchroniser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=200),
        ),
    ]
