# Generated by Django 6.0.4 on 2026-05-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_utilisateur_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detailmvtentrepot',
            name='detailmvten_id_mvt__316925_idx',
        ),
        migrations.RemoveIndex(
            model_name='mvtentrepot',
            name='mvtentrepot_date_mv_66517c_idx',
        ),
        migrations.RenameField(
            model_name='detailmvtentrepot',
            old_name='id_detail_reappro',
            new_name='id_detail_mvt',
        ),
        migrations.RenameField(
            model_name='mvtentrepot',
            old_name='date_mvt_entrepot',
            new_name='date_mvt',
        ),
        migrations.RenameField(
            model_name='mvtentrepot',
            old_name='id_mvt_entrepot',
            new_name='id_mvt',
        ),
        migrations.RenameField(
            model_name='mvtentrepot',
            old_name='mode_mvt_entrepot',
            new_name='mode_mvt',
        ),
        migrations.AddField(
            model_name='detailmvtentrepot',
            name='id_mvt',
            field=models.ForeignKey(db_column='id_mvt', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mvtentrepot'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='detailmvtentrepot',
            index=models.Index(fields=['id_mvt'], name='detailmvten_id_mvt_af393f_idx'),
        ),
        migrations.AddIndex(
            model_name='mvtentrepot',
            index=models.Index(fields=['date_mvt'], name='mvtentrepot_date_mv_46b95e_idx'),
        ),
        migrations.RemoveField(
            model_name='detailmvtentrepot',
            name='id_mvt_entrepot',
        ),
    ]
