# Generated by Django 6.0.4 on 2026-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_detailmvtentrepot_detailmvten_id_mvt__316925_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmvtentrepot',
            name='id_detail_mvt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
