# Generated by Django 6.0.4 on 2026-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_detailmvtentrepot_id_detail_mvt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsvente',
            name='id_detail',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailsvisiteconcurrent',
            name='id_details',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailsvisitecorrection',
            name='id_details',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailsvisiteinvestissement',
            name='id_details',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
