# Generated by Django 6.0.4 on 2026-06-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_detailsvente_id_detail_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mvtentrepot',
            name='mvtentrepot_valider_c385e3_idx',
        ),
        migrations.AddField(
            model_name='mvtentrepot',
            name='date_validation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mvtentrepot',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mvtentrepot',
            index=models.Index(fields=['date_validation'], name='mvtentrepot_date_va_3b0b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mvtentrepot',
            index=models.Index(fields=['statut'], name='mvtentrepot_statut_284724_idx'),
        ),
        migrations.RemoveField(
            model_name='mvtentrepot',
            name='valider',
        ),
    ]
